url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/cv" # the subpath of your site, e.g. /blog
title: "Mrinal Chandra Sarkar"
email: "mrinalvbu@gmail.com"
github: mrinalcs
linkedin: mrinalcs
mobile: +919593457937
